-- MySQL Script generated by MySQL Workbench
-- 01/17/17 12:35:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Jeux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Jeux` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `id_categories` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jeux_categories_idx` (`id_categories` ASC),
  CONSTRAINT `fk_jeux_categories`
    FOREIGN KEY (`id_categories`)
    REFERENCES `new_schema1`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`Bibliotheque_Jeux_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Bibliotheque_Jeux_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_jeux` INT NULL,
  `temps_de_jeux` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jeux_idx` (`id_jeux` ASC),
  INDEX `fk_user_idx` (`id_user` ASC),
  CONSTRAINT `fk_jeux`
    FOREIGN KEY (`id_jeux`)
    REFERENCES `new_schema1`.`Jeux` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `new_schema1`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`User_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`User_User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_User` INT NULL,
  `id_User2` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`id_User` ASC),
  INDEX `fk_user2_idx` (`id_User2` ASC),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_User`)
    REFERENCES `new_schema1`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user20`
    FOREIGN KEY (`id_User2`)
    REFERENCES `new_schema1`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
